blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^portfolio/$', views.portfolio, name='portfolio'),
    url(r'^portfolio/(?P<title>[-\w]+)/$', views.project, name='project'),
    url(r'^blog/(?P<title>[-\w]*)/$', views.blog, name='blog'),
    url(r'^blog/post/(?P<title>[-\w]+)/$', views.post, name='post'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^contact/success/$', views.success, name='success'),
]

games/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<title>[-\w]+)/$', views.game, name='game'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^neverfindthis/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^games/', include('games.urls')),
]

blog/models.py
from django.template.defaultfilters import slugify
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200, unique=True)
    category = models.CharField(max_length=128, default="lifestyle")
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
            self.slug = slugify(self.title)
            super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

games/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

blog/forms.py
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Post
from .forms import ContactForm

# Create your views here.
def index(request):
    return render(request, 'blog/index.html', {})

def about(request):
    return render(request, 'blog/about.html', {})

def portfolio(request):
    return render(request, 'blog/portfolio.html', {})

def blog(request, title):
	if title == 'design' or title == 'lifestyle':
		posts = Post.objects.filter(published_date__lte=timezone.now()).filter(category=title).order_by('published_date')
		return render(request, 'blog/generic_post.html', {'posts':posts, 'category':title})
	else:
		return render(request, 'blog/blog.html', {})

def contact(request):
	if request.method == 'GET':
		form = ContactForm()
	else:
		form = ContactForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			subject = form.cleaned_data['subject']
			message = form.cleaned_data['message']
			try:
				send_mail(subject, message, email, [''])
			except BadHeaderError:
				return HttpResponse('Invalid header found.')
			return redirect('success')
	return render(request, 'blog/contact.html', {'form': form})

def post(request, title):
	context_dict = {}
	try:
		post = Post.objects.all().get(slug=title)
		context_dict['post'] = post
	except Post.DoesNotExist:
		pass
	return render(request, 'blog/post.html', context_dict)

def project(request, title):
	title = title.replace('-','')
	title = title.lower()
	return render(request, "blog/{}.html".format(title), {})

def success(request):
	return render(request, 'blog/success.html', {})

games/views.py
from django.shortcuts import render, redirect

# Create your views here.
def game(request, title):
    return render(request, 'games/{}.html'.format(title), {})

blog/templates/blog/about.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block content %}
<link href="{% static '/css/about.css' %}" rel="stylesheet" type="text/css">
<div class='picture'>
  <img src="{% static '/images/mypicture_small.jpg' %}" alt="My photo"/>
</div>
<div class='description'>
  <i>Greetings!</i>
  <p>
    I'm Alexander Chum, a Computer Science student at the University of Toronto. Officially, I create educational games on high school subjects.<br>
    But really? I share knowledge and passion through virtual realms.<br>
    <br>
    Grit, love, and enthusiasm are 3 words that best describe me.<br>
    <b>Grit</b> - Pushing my limits at work, at the gym, and in the kitchen.<br>
    <b>Love</b> - Working with others, for others, is my motto.<br>
    <b>Enthusiasm</b> - Don't let life get the best of you. Smile!<br>
    <br>
    Want more information? <a href="/contact/">Contact me!</a>
  </p>
</div>
{% endblock %}

blog/templates/blog/blog.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}Alexander Chum's Blog{% endblock %}

{% block content %}
<link href="{% static '/css/blog.css' %}" rel="stylesheet" type="text/css">
<div class="container">
  <a class="game_design" href="/blog/design/" id="gamedesign">smth</a>
  <a class="life_style" href="/blog/lifestyle/" id="lifestyle">smth</a>
</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}Contact Alexander Chum{% endblock %}

{% block content %}
<link href="{% static '/css/contact.css' %}" rel="stylesheet" type="text/css">
<form method="post" class="post-form">

<h2>Contact me on <a href="https://linkedin.com/in/alexanderchum/" target="_blank">LinkedIn</a></br><hr>Or leave a message here!</h2>

  {% csrf_token %}
  <p><label for="id_email">Email*</label>
    <input type="email" name="email" id="id_email" required placeholder="email"/></p>
  <p><label for="id_subject">Subject*</label>
    <input id="id_subject" type="text" name="subject" maxlength="100" required  placeholder="subject"/></p>
  <p><label for="id_message">Message*</label>
    <textarea name="message" id="id_message" required placeholder="message"></textarea></p>
  <div class="form-actions">
  	<button class="button" type="submit">Send</button>
  </div>
</form>
{% endblock %}

blog/templates/blog/generic_post.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}Chum's {{category}} Blog{% endblock %}

{% block content %}
<link href="{% static '/css/generic_post.css' %}" rel="stylesheet" type="text/css">
<div class='container row'>
    {% for post in posts %}
    <div class='posts col-8 col-m-8'>
      <h1><a href="/blog/post/{{post.slug}}/" target="_self">{{post.title}}</a></h1>
      <h5>published: {{post.published_date}}</h5>
      <p>{{ post.text|linebreaksbr }}</p>
    </div>
    {% endfor %}
    <div class='collection col-4 col-m-4'>
	</div>
</div>

{% endblock %}

blog/templates/blog/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Alexander Chum{% endblock %}</title>
  <link href="{% static '/css/header.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
  <div class='header'>
  <div class='bg'>
  </div>
      <div class='name'>
        <a href="/">Alexander</br>Chum</a></ul>
      </div>
      <div class='navbar'>
        <a href="/about/">ABOUT</a>
        <a href="/portfolio/">PORTFOLIO</a>
        <a href="https://github.com/AlexChum/" target="_blank">GITHUB</a>
        <a href="/blog/-/">BLOG</a>
        <a href="/contact/">CONTACT</a>
      </div>
  </div>
  <div class='content'>
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

blog/templates/blog/index.html
{% extends "blog/header.html" %}
{% load staticfiles %}


{% block content %}
<link href="{% static '/css/index.css' %}" rel="stylesheet" type="text/css">
<div class="title">
  <h1>DEVELOPER</h1>
  <h2>Computer Vision, Game Design</h2>
  <p><i>Inspiration feeds Innovation<br>
  	Aspiration nurtures Determination</i></p>
</div>
{% endblock %}

blog/templates/blog/portfolio.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}Alexander Chum's Portfolio{% endblock %}

{% block content %}
<link href="{% static '/css/portfolio.css' %}" rel="stylesheet" type="text/css">
<div class="container">
	<div class="boxes" id="ROP">
		<h1>C.I.S.</h1>
		<h2>Research Opportunity Program</h2>
		<p>The main purpose of this research was to analyze the impact of different game features on the educational aspects of a game. The topic of the game was picked from "difficult" High School subjects and the target audience was high school students.</p>
	    <a href="/portfolio/Research-Opportunity-Program/">Read More...</a>
	</div>
	<div class="boxes" id="BlockBreaker" >
		<h1>Block Breaker</h1>
		<h2>Classic Game <br>
			- Personal Project -</h2>

		<p><span id="title">Block Breaker</span> is a <a href="https://en.wikipedia.org/wiki/Breakout_clone" target="_blank">"Breakout clone"</a>, an arcade game from 1976. Multiple clones were released since then, notably Arkanoid in 1986.<br><br>I have decided to make my own as a small project.<br>*Beware* It is challenging and fast-paced!</p>

	  <a href="/games/blockbreaker/" target="_blank">=== Play&Enjoy! ===</a>
	</div>
	<div class="boxes" id="GravityBlop" href="/portfolio/GravityBlop">
		<h1>Gravity Blop</h1>
		<h2>Mobile Game <br>
			- Personal Project -</h2>
		<p>Gravity Blop is an "endless" mobile game that is currently under development. This game centers around gravitational force. To survive, you need make use of an unpredicatable environment.<br><br>
		*The web model is not optimized but playable.*</p>
	    <a href="/games/gravityblop/" target="_blank">=== Play&Enjoy! ===</a>

	</div>
</div>
<div class="footer">
	<hr>
	<p>*All scripts and assets of the projects can be found on my <a  href="https://github.com/AlexChum/" target="_blank">GitHub</a> profile*</p>
</div>
{% endblock %}

blog/templates/blog/post.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}Chum's Post{% endblock %}

{% block content %}
<link href="{% static '/css/single_post.css' %}" rel="stylesheet" type="text/css">
<div class='container'>
	{% if post %}
    <div>
      <h1>{{post.title}}<h1>
      <b>By: {{post.author}}</b>
      <p><i>Published: {{post.published_date}}</i></p>
      <p>{{ post.text }}</p>
    </div>
  {% else %}
  	<p> no such post {{title}}</p>
  {% endif %}
</div>
{% endblock %}

blog/templates/blog/researchopportunityprogram.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}C.I.S. ROP{% endblock %}

{% block content %}
<link href="{% static '/css/rop.css' %}" rel="stylesheet" type="text/css">
<div class='description'>
  <i>Hello!</i>
  <p>
  Thank you for your interest in my research project!<br>I am currently revising my final report to publish legally permissible data only.<br>For now, please visit this <a href='https://www.utoronto.ca/news/these-video-games-trick-elementary-and-high-school-students-learning-stem'>link</a> for an overview of my research or try the <a href='/games/immune/'>game</a>!.
  </p>
</div>
{% endblock %}

blog/templates/blog/success.html
{% extends "blog/header.html" %}
{% load staticfiles %}

{% block title %}Thank you!{% endblock %}

{% block content %}
<link href="{% static '/css/success.css' %}" rel="stylesheet" type="text/css">
<div class='thankyou'>
  <h1>Thank you for your message!</h1>
  <hr>
  <h3>Enjoy your day!</h3>
  <p>Don't forget to smile :)</p>
</div>
{% endblock %}

games/templates/games/blockbreaker.html
{% extends "games/header.html" %}
{% load staticfiles %}

{% block title %}Block Breaker{% endblock %}

{% block content %}
    <link rel="shortcut icon" href="{% static 'blockbreaker/TemplateData/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'blockbreaker/TemplateData/style.css' %}">
    <script src="{% static 'blockbreaker/TemplateData/UnityProgress.js' %}"></script>  
    <script src="{% static 'blockbreaker/Build/UnityLoader.js' %}"></script>
    <script>
      var gameInstance = UnityLoader.instantiate("gameContainer", "/static/blockbreaker/Build/blockbreaker.json", {onProgress: UnityProgress});
    </script>
    <div class="webgl-content">
      <div id="gameContainer" style="width: 960px; height: 600px"></div>
      <div class="footer">
        <div class="webgl-logo"></div>
        <div class="fullscreen" onclick="gameInstance.SetFullscreen(1)"></div>
        <div class="title">BlockBreaker</div>
      </div>
    </div>
{% endblock %}

games/templates/games/gravityblop.html
{% extends "games/header.html" %}
{% load staticfiles %}

{% block title %}Gravity Blop{% endblock %}

{% block content %}
    <link rel="shortcut icon" href="{% static 'gravityblop/TemplateData/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'gravityblop/TemplateData/style.css' %}">
    <script src="{% static 'gravityblop/TemplateData/UnityProgress.js' %}"></script>  
    <script src="{% static 'gravityblop/Build/UnityLoader.js' %}"></script>
    <script>
      var gameInstance = UnityLoader.instantiate("gameContainer", "/static/gravityblop/Build/gravityblop.json", {onProgress: UnityProgress});
    </script>
    <div class="webgl-content">
      <div id="gameContainer" style="width: 1334px; height: 750px; border: medium solid black;"></div>
      <div class="footer">
        <div class="webgl-logo"></div>
        <div class="fullscreen" onclick="gameInstance.SetFullscreen(1)"></div>
        <div class="title">GravityBlop</div>
      </div>
    </div>
{% endblock %}

games/templates/games/header.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-us">
<head>
  <title>{% block title %}Alexander Chum{% endblock %}</title>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<!-- IF NEEDED THERE CAN BE A HEADER
   <div class='header'>
      <div class='navbar'>
        <a href="/about/">ABOUT</a>
        <a href="/portfolio/">PORTFOLIO</a>
        <a href="https://github.com/Achummy/" target="_blank">GITHUB</a>
        <a href="/blog/">BLOG</a>
        <a href="/contact/">CONTACT</a>
      </div>
  </div> -->
  <div class='content'>
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

games/templates/games/immune.html
{% extends "games/header.html" %}
{% load staticfiles %}

{% block title %}Immune{% endblock %}

{% block content %}
  <link rel="shortcut icon" href="{% static 'immune/TemplateData/favicon.ico' %}">
  <link rel="stylesheet" href="{% static 'immune/TemplateData/style.css' %}">
  <script src="{% static 'immune/TemplateData/UnityProgress.js' %}"></script>  
  <script src="{% static 'immune/Build/UnityLoader.js' %}"></script>
  <script>
    var gameInstance = UnityLoader.instantiate("gameContainer", "/static/immune/Build/immune.json", {onProgress: UnityProgress});
  </script>
  <div class="webgl-content">
    <div id="gameContainer" style="width: 1440px; height: 900px"></div>
    <div class="footer">
      <div class="webgl-logo"></div>
      <div class="fullscreen" onclick="gameInstance.SetFullscreen(1)"></div>
      <div class="title">Immune</div>
    </div>
  </div>
{% endblock %}